name: stripe_sdk_plus
description: The only native Stripe library for Flutter. Has complete support for SCA/PSD2, payment intents and the newest Stripe features.
version: 0.2.0
homepage: https://github.com/ezet/stripe_sdk

environment:
  sdk: '>=3.0.5 <4.0.0'
  # flutter: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

  awesome_card: ^1.1.7
  collection: ^1.17.1
  credit_card_validator: ^2.1.0
  http: ^0.13.6 #http: ^1.0.0
  url_launcher: ^6.1.11
  mask_text_input_formatter: ^2.4.0
  #  flutter_slidable: ^1.2.0
  simple_animations: ^5.0.2
  webview_flutter: ^3.0.4
  universal_html: ^2.2.3


dev_dependencies:
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

false_secrets:
  - example/**
