name: stripe_sdk_plus
description: Native Stripe library for Flutter. Has complete support for SCA/PSD2, payment intents and the newest Stripe features.
version: 1.1.0
homepage: https://github.com/NifalNizar/stripe_sdk_plus
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  awesome_card: ^1.1.7
  collection: ^1.17.1
  credit_card_validator: ^2.1.0
  http: ^1.1.0
  url_launcher: ^6.1.11
  mask_text_input_formatter: ^2.4.0
  simple_animations: ^5.0.2
  webview_flutter: ^3.0.4 # webview_flutter: ^4.2.2
  universal_html: ^2.2.3

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

false_secrets:
  - example/**
