name: Publish

on:
  push:
    branches:
      - master
      - workflow

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dart and Flutter Package Publisher
        uses: k-paxian/dart-package-publisher@v1.2
        with:
          skiptests: false
          dryRunOnly: false
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
